-- 0049 (antes 0034, número duplicado) · Poblar sii_comuna_code para comunas que no lo tenían
-- Códigos extraídos de los nombres de archivo parquet de catastral.cl
UPDATE chile_comunas SET sii_comuna_code = '6110' WHERE name = 'San Vicente de Tagua Tagua' AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '6102' WHERE name = 'Machalí'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '7303' WHERE name = 'Colbún'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '7106' WHERE name = 'Vichuquén'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '10111' WHERE name = 'Río Bueno'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '8101' WHERE name = 'Chillán'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5309' WHERE name = 'Concón'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5307' WHERE name = 'Puchuncaví'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5304' WHERE name = 'Quilpué'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5302' WHERE name = 'Viña del Mar'               AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5301' WHERE name = 'Valparaíso'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '8401' WHERE name = 'Los Ángeles'                AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '8201' WHERE name = 'Concepción'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '9216' WHERE name = 'Pucón'                      AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14605' WHERE name = 'Alhué'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16153' WHERE name = 'San Ramón'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16163' WHERE name = 'San Joaquín'               AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14109' WHERE name = 'Maipú'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '15105' WHERE name = 'Ñuñoa'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16162' WHERE name = 'Pedro Aguirre Cerda'       AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14602' WHERE name = 'María Pinto'               AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '15152' WHERE name = 'Peñalolén'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16303' WHERE name = 'San José de Maipo'         AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14603' WHERE name = 'Curacaví'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14127' WHERE name = 'Conchalí'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14157' WHERE name = 'Estación Central'          AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5308' WHERE name = 'Juan Fernández'             AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '8116' WHERE name = 'Yungay'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '8109' WHERE name = 'San Carlos'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '8107' WHERE name = 'Cobquecura'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '8106' WHERE name = 'Portezuelo'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '8103' WHERE name = 'Coihueco'                   AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5701' WHERE name = 'Los Andes'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5601' WHERE name = 'San Felipe'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5506' WHERE name = 'Limache'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5505' WHERE name = 'La Cruz'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5503' WHERE name = 'Hijuelas'                   AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5502' WHERE name = 'Nogales'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5501' WHERE name = 'Quillota'                   AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5406' WHERE name = 'Algarrobo'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5402' WHERE name = 'Santo Domingo'              AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5401' WHERE name = 'San Antonio'                AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5306' WHERE name = 'Quintero'                   AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5305' WHERE name = 'Casablanca'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5303' WHERE name = 'Villa Alemana'              AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5205' WHERE name = 'Papudo'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '5204' WHERE name = 'Zapallar'                   AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '1201' WHERE name = 'Iquique'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '6304' WHERE name = 'La Estrella'                AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '6302' WHERE name = 'Navidad'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '6301' WHERE name = 'Pichilemu'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '6205' WHERE name = 'Santa Cruz'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '6201' WHERE name = 'San Fernando'               AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '6111' WHERE name = 'Pichidegua'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '6109' WHERE name = 'Las Cabras'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '6107' WHERE name = 'Codegua'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '6103' WHERE name = 'Graneros'                   AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '6101' WHERE name = 'Rancagua'                   AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '7301' WHERE name = 'Linares'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '7206' WHERE name = 'Maule'                      AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '7201' WHERE name = 'Talca'                      AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '7104' WHERE name = 'Rauco'                      AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '12205' WHERE name = 'Punta Arenas'              AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '12103' WHERE name = 'Torres del Paine'          AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '10112' WHERE name = 'Lago Ranco'                AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '10108' WHERE name = 'Panguipulli'               AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '10105' WHERE name = 'Futrono'                   AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '10101' WHERE name = 'Valdivia'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '10401' WHERE name = 'Castro'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '10305' WHERE name = 'Frutillar'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '10303' WHERE name = 'Puerto Varas'              AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '10301' WHERE name = 'Puerto Montt'              AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '10201' WHERE name = 'Osorno'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '4101' WHERE name = 'La Serena'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '9201' WHERE name = 'Temuco'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '9215' WHERE name = 'Villarrica'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14601' WHERE name = 'Melipilla'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14604' WHERE name = 'San Pedro'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14155' WHERE name = 'Lo Prado'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16131' WHERE name = 'La Granja'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16165' WHERE name = 'El Bosque'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16154' WHERE name = 'La Pintana'                AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14166' WHERE name = 'Cerrillos'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16401' WHERE name = 'San Bernardo'              AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16403' WHERE name = 'Buin'                      AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14158' WHERE name = 'Huechuraba'                AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14114' WHERE name = 'Quilicura'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14113' WHERE name = 'Renca'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14107' WHERE name = 'Quinta Normal'             AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14501' WHERE name = 'Talagante'                 AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '13167' WHERE name = 'Independencia'             AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16106' WHERE name = 'San Miguel'                AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '15151' WHERE name = 'Macul'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14202' WHERE name = 'Lampa'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '13135' WHERE name = 'Santiago'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '13159' WHERE name = 'Recoleta'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14203' WHERE name = 'Tiltil'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14502' WHERE name = 'Isla de Maipo'             AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16301' WHERE name = 'Puente Alto'               AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16302' WHERE name = 'Pirque'                    AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16402' WHERE name = 'Calera de Tango'           AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '16404' WHERE name = 'Paine'                     AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14156' WHERE name = 'Cerro Navia'               AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14503' WHERE name = 'El Monte'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14505' WHERE name = 'Padre Hurtado'             AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
UPDATE chile_comunas SET sii_comuna_code = '14111' WHERE name = 'Pudahuel'                  AND (sii_comuna_code IS NULL OR sii_comuna_code = '');
